#! /bin/sh

PATH=/usr/local/bin:/usr/bin:/bin:/usr/bin/X11

if [ -f /usr/local/cnts/epics/base/startup/Site.bashrc ]; then
  . /usr/local/cnts/epics/base/startup/Site.bashrc
fi
FPATH=/usr/local/cnts/epics/operations/var

DATESTR=""

if [ -x ` which caget ` ]; then

#	OUTPUT=' caget caget CCC:OpsDisplay:Operator:TimeStamp -t 2>/dev/null '
	OUTPUT=` caget CCC:OpsDisplay:Operator:TimeStamp -t 2>/dev/null `
#echo $OUTPUT

	if [ $? -ne 0 ];then
#echo NOT using caget
		DATESTR=` date +%Y.%b.%d.%H.%m `
	else
#echo using caget
#		DATESTR=` caget CCC:OpsDisplay:Operator:TimeStamp -t `
		DATESTR=${OUTPUT}
	fi

else
#echo no caget
	DATESTR=` date +%Y.%b.%d.%H.%m `.no_caget
fi

echo $DATESTR

exit 

if [ -f $FPATH/log/system/temp.log ]; then 
	cat $FPATH/log/system/temp.log >> "$FPATH/log/system/opr$DATESTR.log"
fi

if [ -f $FPATH/whiteboard.txt ]; then 
	cat $FPATH/whiteboard.txt >> "$FPATH/log/system/opr$DATESTR.log"
fi


if [ ! -f $FPATH/log/blank.log ]; then
	touch $FPATH/log/blank.log
fi
cp $FPATH/log/blank.log $FPATH/log/system/temp.log

